import type { Project } from '@/lib/portfolio-types'

export const selectedProjects: readonly Project[] = [
  {
    id: 'unipm',
    name: 'UniPM',
    type: 'Team capstone',
    role: 'Backend and retrieval contributor',
    summary: 'A preventive-maintenance workflow for university assets, schedules, inspections, and multi-row maintenance forms.',
    workflow: 'Assets and schedules lead into inspections. A maintenance form moves from draft to submitted to acknowledged, with only acknowledged rows published to official history and retrieval.',
    contributions: [
      'Built policy-protected ASP.NET Core workflows for assets, schedules, inspections, and the maintenance-form lifecycle.',
      'Implemented history retrieval with SQL Server Full-Text Search, serialized embeddings, bounded candidates, application cosine similarity, and Reciprocal Rank Fusion.',
    ],
    technologies: ['ASP.NET Core', 'React', 'SQL Server', 'SQL Server Full-Text Search', 'Embeddings', 'Reciprocal Rank Fusion'],
    repository: 'https://github.com/lucifron28/UniPM',
    media: [{ src: '/projects/unipm/cover.svg', alt: 'UniPM repository-derived workflow from university assets and schedules through inspections and maintenance review', width: 1600, height: 1000, kind: 'diagram' }],
    caseStudy: {
      status: 'Academic capstone MVP · 2026–present',
      scope: 'University preventive-maintenance workflow and source-bounded maintenance-history retrieval.',
      problem: 'Maintenance records need a controlled handoff from operational forms into an official history that can be searched without treating drafts or unacknowledged submissions as authoritative.',
      team: 'Team capstone. My verified focus was backend workflow and retrieval work.',
      architecture: [
        'React and TypeScript client requests are served by an ASP.NET Core API backed by SQL Server.',
        'Policy-protected API paths cover assets, schedules, inspections, and maintenance review records.',
        'Retrieval combines SQL Server Full-Text Search candidates with serialized embedding metadata, application cosine similarity, and Reciprocal Rank Fusion.',
      ],
      technicalDecisions: [
        'Only acknowledged maintenance rows enter official history and retrieval.',
        'Candidate retrieval is bounded before semantic scoring, with an explicit lexical fallback when semantic services are unavailable.',
        'Query vectors are transient and are not stored as user history.',
      ],
      securityAndData: [
        'The repository documents JWT authentication and policy-based authorization across five roles.',
        'Fictional users and synthetic maintenance records keep the capstone data separate from institutional production data.',
      ],
      reliabilityAndOperations: [
        'The repository includes migrations, health checks, CI, and a documented rebuild command for retrieval artifacts.',
        'The rebuild command is documented as idempotent. General HTTP workflows are not presented as idempotent.',
      ],
      testing: ['Deterministic fixtures and tests cover the documented retrieval and maintenance workflow assumptions, including 84 fixture records in the current CV evidence.'],
      limitations: ['This is an academic capstone MVP with fictional development records and no verified institutional production deployment.', 'It does not provide a chatbot, autonomous diagnosis, or predictive-maintenance decisions. Corrected-action handoff is outside the current scope.'],
      mediaNote: 'The current visual is a repository-derived workflow diagram. A stable running-app capture was not available during this pass.',
    },
  },
  {
    id: 'sidekick',
    name: 'Sidekick',
    type: 'Team bootcamp capstone',
    role: 'Backend authentication and React delivery',
    summary: 'A talent marketplace for profiles, skills, gigs, applications, and contracts.',
    workflow: 'Users create profiles and skills, browse gigs, submit applications, and manage contracts.',
    contributions: [
      'Implemented ASP.NET Core Identity bearer authentication with an HttpOnly refresh-cookie flow.',
      'Connected React profile, gig, application, and contract flows to PostgreSQL; Docker Compose starts the client, API, and database with health-aware startup.',
    ],
    technologies: ['ASP.NET Core', 'ASP.NET Core Identity', 'React', 'PostgreSQL', 'Docker Compose'],
    repository: 'https://github.com/lucifron28/openit-bootcamp-capstone',
    media: [{ src: '/projects/sidekick/cover.svg', alt: 'Sidekick repository-derived marketplace workflow from profiles and skills through gigs and contracts', width: 1600, height: 1000, kind: 'diagram' }],
    caseStudy: {
      status: 'Bootcamp capstone · 2026',
      scope: 'Talent marketplace workflows for profiles, skills, gigs, applications, and contracts.',
      problem: 'A marketplace needs related user and work records to move through a small set of understandable workflows while the team can run the API, client, and database together.',
      team: 'Team bootcamp capstone. My verified focus was backend authentication and React delivery.',
      architecture: [
        'A React client communicates with an ASP.NET Core API using an Entity Framework Core data model backed by PostgreSQL.',
        'ASP.NET Core Identity supplies bearer authentication and the repository exposes profile, skill, gig, application, and contract entities.',
        'Docker Compose runs the client, API, and database with a PostgreSQL health check before API startup.',
      ],
      technicalDecisions: ['Kept access credentials in the client flow while storing the refresh credential in an HttpOnly cookie.', 'Used the existing Identity endpoint and bearer-token support instead of describing the system as a custom JWT implementation.'],
      securityAndData: ['ASP.NET Core Identity handles authentication and security-stamp validation for the refresh flow.', 'PostgreSQL persists the marketplace and Identity records.'],
      reliabilityAndOperations: ['The Compose setup includes a health-aware dependency for PostgreSQL and a dedicated API health endpoint.'],
      testing: ['The repository provides the capstone client/API setup and local Compose workflow. No production uptime or deployment claim is made here.'],
      limitations: ['This is a bootcamp capstone. No public production deployment is verified in the repository evidence reviewed for this pass.'],
      mediaNote: 'The current visual is a repository-derived workflow diagram. A stable running-app capture was not available during this pass.',
    },
  },
  {
    id: 'enverga-arena',
    name: 'Enverga Arena',
    type: 'Solo project',
    role: 'Sole developer',
    summary: 'An MSEUF intramurals system for verified tryouts, department review, rosters, registrations, results, medal tallies, and news.',
    workflow: 'Students apply for tryouts; department representatives review athletes and rosters; administrators manage results, medals, news, and reviewed AI recaps.',
    contributions: [
      'Built Django REST Framework tryout, roster, registration, result, medal, and role workflows.',
      'Added domain OTP, hashed OTP storage, server-side Turnstile verification, rate limiting, duplicate protection, and human review for AI recap publication.',
    ],
    technologies: ['Django REST Framework', 'React', 'TypeScript', 'SQLite', 'Cloudflare Turnstile', 'Brevo'],
    repository: 'https://github.com/lucifron28/EnvergaArena',
    media: [{ src: '/projects/enverga-arena/cover.svg', alt: 'Enverga Arena repository-derived workflow from verified tryouts and registrations through reviewed results and recaps', width: 1600, height: 1000, kind: 'diagram' }],
    caseStudy: {
      status: 'Solo project · 2026',
      scope: 'MSEUF intramurals tryout, team, scheduling, result, medal, news, and reviewed-recap workflows.',
      problem: 'A public-facing intramurals system has different responsibilities for students, department representatives, and administrators, so application review and official publication need explicit boundaries.',
      team: 'Solo project. I built the application and its backend/frontend workflow boundaries.',
      architecture: ['React and TypeScript client with a Django REST Framework API and the current local SQLite database.', 'Tryout, roster, registration, schedule, result, medal, and news workflows are separated by role.'],
      technicalDecisions: ['Student tryouts are verified through the student-domain email and OTP flow before review.', 'AI recap generation creates a draft for administrator review rather than publishing generated text directly.', 'PostgreSQL is a future direction in the repository, not the current local database claim.'],
      securityAndData: ['Access tokens are held in frontend memory and refresh credentials are set by the backend in an HttpOnly cookie.', 'OTP values are hashed, Turnstile is verified server-side, and rate limiting plus duplicate protection cover the public tryout path.'],
      reliabilityAndOperations: ['Role-specific workflows and explicit review states keep official results and recaps under administrator control.'],
      testing: ['The repository documents the authentication, tryout, roster, result, and recap boundaries reviewed for this case study.'],
      limitations: ['The current project uses SQLite locally. PostgreSQL is documented as a future direction, not a current deployment.', 'AI recap text remains a draft until human review and approval.'],
      mediaNote: 'The current visual is a repository-derived workflow diagram. A stable running-app capture was not available during this pass.',
    },
  },
  {
    id: 'studylens',
    name: 'StudyLens',
    type: 'Solo Android final project',
    role: 'Sole developer',
    summary: 'A native Android learning companion for course modules, progress, notes, board scans, summaries, flashcards, quizzes, and tutor features.',
    workflow: 'Students read modules, track progress, capture classroom boards, edit OCR text, and review study materials.',
    contributions: [
      'Built native Android module, progress, note, OCR, summary, flashcard, quiz, and tutor workflows.',
      'Connected Jetpack Compose to JWT-secured DRF/PostgreSQL services and kept AI credentials behind the backend service layer.',
    ],
    technologies: ['Kotlin', 'Jetpack Compose', 'CameraX', 'ML Kit OCR', 'Retrofit', 'Django REST Framework'],
    repository: 'https://github.com/lucifron28/StudyLens',
    media: [{ src: '/projects/studylens/studylens-home.png', alt: 'StudyLens Android home screen showing tasks, recent board-scan activity, and Home, Subjects, Scans, and Profile navigation', width: 720, height: 1608, kind: 'screen' }],
    caseStudy: {
      status: 'Solo Android final project · 2026',
      scope: 'Native Android learning companion with course content, OCR, progress, study tools, and a server-side AI boundary.',
      problem: 'Students need one mobile workflow for reading course material, capturing classroom boards, and turning reviewed content into study aids without exposing provider credentials in the app.',
      team: 'Solo project. I built the Android client and the supporting API integration.',
      architecture: ['A Kotlin and Jetpack Compose Android client uses CameraX, ML Kit OCR, Retrofit, and local Android storage integrations.', 'The client communicates with a Django REST Framework API backed by PostgreSQL for user-owned course and study records.', 'The backend service layer owns configured AI provider calls and credentials.'],
      technicalDecisions: ['Kept OCR text editable before it becomes a study input.', 'Put AI calls behind the API so the Android app does not hold provider credentials.', 'Scoped records to the authenticated user in the backend query and ownership paths.'],
      securityAndData: ['The API uses JWT authentication and user-scoped records.', 'The Android client communicates with the server boundary for AI-assisted summaries, flashcards, quizzes, and tutor features.'],
      reliabilityAndOperations: ['The repository includes backend API documentation, Docker/PostgreSQL development configuration, and explicit Android/backend module boundaries.'],
      testing: ['The current repository contains the Android and backend build surfaces reviewed for this case study. No Play Store release claim is made.'],
      limitations: ['This portfolio describes the repository implementation and does not claim a Play Store release or production deployment.'],
    },
  },
]

export const additionalProjects: readonly Project[] = [
  {
    id: 'scrybe-sync',
    name: 'ScrybeSync',
    type: 'Solo project',
    role: 'Sole developer',
    summary: 'A Dockerized transcription and linked-note app that moves Whisper transcription and LLM summarization into Celery background workers.',
    workflow: 'Users upload audio or video, review transcription output, and connect notes to generated summaries.',
    contributions: [
      'Built the Django REST Framework, Celery, Redis, PostgreSQL, and Docker Compose workflow for asynchronous transcription and summarization.',
      'Kept transcripts and linked notes scoped to the authenticated owner in the API views and serializers.',
    ],
    technologies: ['Django REST Framework', 'Celery', 'Redis', 'PostgreSQL', 'Docker Compose', 'Whisper'],
    repository: 'https://github.com/lucifron28/ScrybeSync',
    media: [{ src: '/ScrybeSync.png', alt: 'ScrybeSync transcription and linked-note project interface', width: 1600, height: 900, kind: 'screen' }],
  },
  {
    id: 'aquest',
    name: 'AQuest',
    type: 'Open iT Codefest project',
    role: 'Codefest project contributor',
    summary: 'A gamified team project-management app with projects, tasks, members, statistics, and an AI coach.',
    workflow: 'Teams organize projects and tasks, track activity and statistics, and use the AI coach for project-management guidance.',
    contributions: [
      'Contributed to project, task, member, statistics, and AI coach workflows in the Codefest application.',
      'Kept achievement functionality labeled as not fully implemented, matching the repository documentation.',
    ],
    technologies: ['SvelteKit', 'Svelte', 'Django REST Framework', 'PostgreSQL', 'JWT', 'Docker Compose'],
    repository: 'https://github.com/lucifron28/AQuest',
    media: [{ src: '/AQuest.png', alt: 'AQuest Codefest project-management interface', width: 1600, height: 900, kind: 'screen' }],
  },
]

export function getProjectById(id: string) {
  return selectedProjects.find((project) => project.id === id)
}
